name: NoNameRadio CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Tests
      run: ./gradlew assembleFreeDebug assemblePlayDebug -x test -x lint
