name: Build & Publish Debug APK

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: "17"
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Debug APK
        run: ./gradlew assembleFreeDebug assemblePlayDebug -x test -x lint

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/*/debug/NoNameRadio*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
